// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5w2MFIV0D4xuvVi5iUxttw73fSvOIBU',
    appId: '1:228886148344:web:3fa1170ab8f97fe4dc770d',
    messagingSenderId: '228886148344',
    projectId: 'salefulbto',
    authDomain: 'salefulbto.firebaseapp.com',
    storageBucket: 'salefulbto.firebasestorage.app',
  );
}
